server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
