
server: 
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb #H2서버의 JDBC URL주소를 이렇게 바꾼것.
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true      